title: Harsha S. Bhat
description: Harsha S. Bhat's webpage
sourcecode: https://github.com/gchauras/www
permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: ""    # the base hostname & protocol for your site
baseurl: ""                  # the subpath of your site, e.g. /blog
# url: "localhost"             # for local testing
# baseurl: ""

author:
    name: Harsha S. Bhat
    scholar: ZHskR34AAAAJ

# Build settings
markdown: kramdown
highlighter: rouge

